version: "3.9"
services:
  grafana:
    links:
      - grafana_db:grafana_db
    image: grafana/grafana:latest
    user: "$UID:$GID"
    volumes:
      - ./grafana:/var/lib/grafana:rw
    environment:
      - GF_DATABASE_HOST=grafana_db:3306
      - GF_DATABASE_NAME=grafanadb
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=test1234
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_MAX_OPEN_CONN=300
    ports:
      - "127.0.0.1:3000:3000"
    depends_on: ["grafana_db"]
  grafana_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: grafanadb
      MYSQL_USER: grafana
      MYSQL_PASSWORD: test1234
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --innodb_monitor_enable=all,
        --max-connections=1001,
      ]
    ports:
      - "127.0.0.1:3306:3006"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10